services:
    negromovich.authentication.firebase.factory_base:
        class: Kreait\Firebase\Factory
        public: false

    negromovich.authentication.firebase.factory:
        class: Kreait\Firebase\Factory
        factory: [ '@negromovich.authentication.firebase.factory_base', 'withServiceAccount' ]
        # arguments defined in extension

    negromovich.authentication.firebase.auth:
        class: Kreait\Firebase\Auth
        factory: [ '@negromovich.authentication.firebase.factory', 'createAuth' ]

    Negromovich\AuthenticationBundle\Security\FirebaseAuthenticator:
        arguments:
            - '@Negromovich\AuthenticationBundle\Repository\AuthUserRepositoryInterface'
            - '@negromovich.authentication.firebase.auth'
            - '@router.default'

    Negromovich\AuthenticationBundle\Security\FirebaseLogoutListener:
        arguments:
            - '@Negromovich\AuthenticationBundle\Controller\LoginController'
        tags:
            -   name: 'kernel.event_listener'
                event: 'Symfony\Component\Security\Http\Event\LogoutEvent'
                dispatcher: security.event_dispatcher.main

    Negromovich\AuthenticationBundle\Repository\AuthUserRepository:
        class: Negromovich\AuthenticationBundle\Repository\AuthUserRepository
        arguments: [ '@doctrine' ]
        tags: [ 'doctrine.repository_service' ]

    Negromovich\AuthenticationBundle\Repository\AuthUserRepositoryInterface: '@Negromovich\AuthenticationBundle\Repository\AuthUserRepository'

    Negromovich\AuthenticationBundle\Controller\LoginController:
        arguments:
            - '@Negromovich\AuthenticationBundle\DependencyInjection\AuthConfig'
            - '@twig'
        tags: [ 'controller.service_arguments' ]

    Negromovich\AuthenticationBundle\Controller\AdminController:
        arguments:
            - '@Negromovich\AuthenticationBundle\Repository\AuthUserRepositoryInterface'
            - '%security.role_hierarchy.roles%'
        calls:
            - { method: setContainer, arguments: [ '@service_container' ] }
        tags: [ 'controller.service_arguments' ]

    Negromovich\AjaxFileBundle\Provider\FileObjectFactory: ~
